name: Test Secrets and Variables
on: push
jobs:
  display_values:
    runs-on: ubuntu-latest
    outputs:
      MON_RETOUR: ${{steps.set-result.outputs.result}}
    steps:
      - run: |
          echo "${{ secrets.DATABASE_PASSWORD }}"
          echo "${{ vars.VERSION }}"
      - name: GitHub Script
        uses: actions/github-script@v7.0.1
        id: set-result
        with:
          # The script to run
          script: return "Mon retour";
  display_return:
    runs-on: ubuntu-latest
    needs: display_values
    steps:
      - run: echo ${{ needs.display_values.outputs.MON_RETOUR }}
